logging:
  level:
    org.springframework.web: DEBUG
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
server:
  port: 8088